### ISSUE TITLE
README does not describe the build dependence on vulkan.h

### ISSUE THREAD

**Issue by dneto0** [Igalia/vkrunner#15]

**Comment by dneto0** [comment]
(Sorry, this submitted before I was ready.)

The README does not describe the build dependence on vulkan.h

It should say that vulkan.h should be found in one of two ways:

1.  via pkg-config (I'm not clear on the details), or
2. Finding the vulkan.h via a regular source include.  For example, I downloaded the vulkan headers and then pointed at them with -DCMAKE_REQUIRED_INCLUDES=<dir-to-vulkan-parent-dir>

**Comment by jaebaek** [comment]
Even though we give `-DCMAKE_REQUIRED_INCLUDES=` argument, it fails when the compiler accesses `vulkan/vulkan.h` because the given path is not included in `include_directories`. See [here](https://github.com/Igalia/vkrunner/blob/master/vkrunner/CMakeLists.txt#L3).

Why don't we give an option like `cmake -DVULKAN_INCLUDE_PATH:STRING=...` or use an environment variable e.g., `VULKAN_INCLUDE_PATH` ?

**Comment by bpeel** [comment]
I’m not particularly experienced with CMake so I’m not sure what the standard way to do this is. It seems like there should just be a general way to add global include paths when invoking CMake. Perhaps one way to do it could be just to set the CFLAGS environment variable?

Please take a look at this [proposed patch](https://github.com/Igalia/vkrunner/commit/730efa8f94fc1ad2229d1937183392b7178fa862) for the README and let me know if this meets your requirements.

**Comment by jaebaek** [comment]
The [proposed patch](https://github.com/Igalia/vkrunner/commit/730efa8f94fc1ad2229d1937183392b7178fa862) solves this issue. I added minor comments on it. Thanks.
