### ISSUE TITLE
Support command line options for shader compilers

### ISSUE THREAD

**Issue by jaebaek** [Igalia/vkrunner#22]
There might be some use cases to test various compiler options with a single VkRunner script e.g., glslangValidator options.
Currently, users cannot change those options (https://github.com/Igalia/vkrunner/blob/master/vkrunner/vr-pipeline.c#L184).

It would be nice if we support
- Command line arguments of VkRunner that will be shader compiler options.
- VkRunner command used in VkRunner script to set up shader compiler options.

**Comment by bpeel** [comment]
Can you give an example of a situation where this is useful?

One way to work around the problem outside of VkRunner scripts could be to make a compiler wrapper script and point to it with the `PIGLIT_GLSLANG_VALIDATOR_BINARY` environment variable.

I’m not so keen on being able to set the command line options within a VkRunner script because that would prevent us from eventually switching to linking to the library version of glslang one day if we decide that it’s better.

**Comment by jaebaek** [comment]
I agree with your opinion. Just specifying the options through `PIGLIT_GLSLANG_VALIDATOR_BINARY` environment variable would be enough now. Let me close this issue and reopen it if we have that specific use cases later.
