### ISSUE TITLE
Support Vulkan 1.1

### ISSUE THREAD

**Issue by jaebaek** [Igalia/vkrunner#29]
If we provide users with an option to set the version of vulkan e.g., 1.0 or 1.1 in VkRunner script, it would be nice. For example:

```
[require]
vulkan version 1.1.70
```
or
```
[vulkan version]
1.1.70
```

**Comment by samuelig** [comment]
shader_runner does the following for GL and GLSL:

```
[require]
GL >= 4.5 
GLSL >= 4.50
```
Probably something like this is enough:
```
[require]
vulkan  1.1.70 
```

**Comment by bpeel** [comment]
It might be worth clarifying what this option would do. I guess it would be the following:

- Set `VkInstanceCreateInfo.apiVersion` during the context creation.
- Make the test report `VR_RESULT_SKIP` if it can’t find a device that supports that version.
- Set the `--target-env` option for the GLSL compiler so that it can generate SPIRV-1.3 or use whatever features from Vulkan 1.1.
- Probably have to do the same thing in `precompile-script.py`

**Comment by hikiko** [comment]
With the latest commits vkrunner allows selecting the version in the [require] section like follows:

```
[require]
vulkan <major>.<minor>.<patch>
```

and so I am closing this issue.
